# Generated by Django 2.2.10 on 2021-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_of_submission',
            field=models.DateTimeField(default='2000-12-02'),
        ),
    ]
