# Generated by Django 2.2.10 on 2021-04-30 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignment_date_of_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_of_submission',
            field=models.DateTimeField(default=datetime.date(2021, 4, 30)),
        ),
    ]
