# Generated by Django 2.2.10 on 2021-05-03 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210430_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_of_submission',
            field=models.DateTimeField(default=datetime.date(2021, 5, 3)),
        ),
    ]
